# Generated by Django 3.2.5 on 2021-07-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210716_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='profilePic',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='projecturl',
            new_name='projectUrl',
        ),
    ]
