# Generated by Django 3.2.5 on 2021-07-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210720_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profilePic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
    ]
