# Generated by Django 3.2.5 on 2021-07-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_profiles_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoringaMerch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('bio', models.TextField()),
                ('projects', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
