# Generated by Django 3.2.5 on 2021-07-21 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_moringamerch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoringaMerch',
        ),
    ]
